### PR TITLE
Mellanox system drivers backport to kernel 4.9

### PR DESCRIPTION
**Pull request by MellanoxBSP**
This series of patches introduces support for Mellanox systems.
Most of the patches is a backporting from the kernels 4.10 - 4.14
for Mellanox system drivers that have been applied upstream and
a few patches contain current Mellanox upstream work - patches
which are in review process for acceptances for kernels 4.16 - 4.17.
This series introduces Mellanox i2c controller, mux, platform,
hotplug, led, asic drivers, TI voltage controller driver and the
extension of Mellanox kernel config.

In series file all the patches are listed and all old patches, relevant
for old 3.16 kernel are commented out.

Signed-off-by: Vadim Pasternak <vadimp@melanox.com>

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by MellanoxBSP** [comment]
Hi Guohan,
I added the full list of Mellanox kernel patches, accepted to upstream
between 4.10 - 4.15 in commit text, as we closed.

Thanks,
VAdim.

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
