### PR TITLE
[Mellanox]Port the Mellanox kernel patches to 4.19

### PR DESCRIPTION
**Pull request by stephenxs**
1. Port the Mellanox kernel patches to Linux kernel 4.19 which is used by Debian 10.
2. A compiling error in driver-hwmon-pmbus-xxx-dps460 patches has also been fixed in this PR.

### CODE REVIEW

**Comment by lguohan** [comment]
should i do squash merge or not? can you make your patch more meanful so that I do not need to do squash merge?

**Comment by stephenxs** [comment]
> should i do squash merge or not? can you make your patch more meanful so that I do not need to do squash merge?

Can you do a squash merge?
I can squash all the commits into one but need to raise another PR in that case.

**Comment by stephenxs** [comment]
> should i do squash merge or not? can you make your patch more meanful so that I do not need to do squash merge?

Ok, I'll squash them.

**Comment by stephenxs** [comment]
> should i do squash merge or not? can you make your patch more meanful so that I do not need to do squash merge?

Done.

**Pull request merged**
